[package]
name    = "wifi"
version = "0.1.0"
edition = "2021"
authors = ["Sergio Gasquez <sergio.gasquez@gmail.com>"]

[dependencies]
anyhow = "1.0.86"
esp-idf-svc = "=0.48"
log         = "=0.4.20 "
heapless = "0.8"
[build-dependencies]
embuild = "=0.31.4"

[dev-dependencies]
toml-cfg = "=0.2.0"
